name: exams/f22 CI

on:
  push:
    paths:
      - 'exams/f22/**' # Only trigger on push to the "exams/f22" folder
    branches: [ "main" ]
  pull_request:
    paths:
      - 'exams/f22/**' # Only trigger on pull request involving changes in the "exams/f22" folder
    branches: [ "main" ]
  workflow_dispatch: # Enable manual triggering

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}/exams/f22

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
